// Every audio file in src/assets/audio (CC0, see CREDITS.md there) as a Metro
// asset module id. Kept apart from the sound table so headless tests never
// require an mp3.

/* eslint-disable @typescript-eslint/no-require-imports */
export const AUDIO_FILES = {
  music_fever_loop: require("../assets/audio/music/music_fever_loop.mp3"),
  music_game_loop: require("../assets/audio/music/music_game_loop.mp3"),
  music_menu_loop: require("../assets/audio/music/music_menu_loop.mp3"),
  sfx_bomb_shoot: require("../assets/audio/sfx/sfx_bomb_shoot.mp3"),
  sfx_bomb_stick: require("../assets/audio/sfx/sfx_bomb_stick.mp3"),
  sfx_bomb_tick: require("../assets/audio/sfx/sfx_bomb_tick.mp3"),
  sfx_bomb_tick_warning: require("../assets/audio/sfx/sfx_bomb_tick_warning.mp3"),
  sfx_boss_appear: require("../assets/audio/sfx/sfx_boss_appear.mp3"),
  sfx_boss_defeated: require("../assets/audio/sfx/sfx_boss_defeated.mp3"),
  sfx_boss_hit: require("../assets/audio/sfx/sfx_boss_hit.mp3"),
  sfx_boss_shield_break: require("../assets/audio/sfx/sfx_boss_shield_break.mp3"),
  sfx_chain_explosion: require("../assets/audio/sfx/sfx_chain_explosion.mp3"),
  sfx_combo_1: require("../assets/audio/sfx/sfx_combo_1.mp3"),
  sfx_combo_2: require("../assets/audio/sfx/sfx_combo_2.mp3"),
  sfx_combo_3: require("../assets/audio/sfx/sfx_combo_3.mp3"),
  sfx_combo_4: require("../assets/audio/sfx/sfx_combo_4.mp3"),
  sfx_combo_5: require("../assets/audio/sfx/sfx_combo_5.mp3"),
  sfx_combo_6: require("../assets/audio/sfx/sfx_combo_6.mp3"),
  sfx_combo_blip: require("../assets/audio/sfx/sfx_combo_blip.mp3"),
  sfx_deflect: require("../assets/audio/sfx/sfx_deflect.mp3"),
  sfx_dodge_whoosh: require("../assets/audio/sfx/sfx_dodge_whoosh.mp3"),
  sfx_fever_end: require("../assets/audio/sfx/sfx_fever_end.mp3"),
  sfx_fever_start: require("../assets/audio/sfx/sfx_fever_start.mp3"),
  sfx_freeze: require("../assets/audio/sfx/sfx_freeze.mp3"),
  sfx_game_over: require("../assets/audio/sfx/sfx_game_over.mp3"),
  sfx_knockback_whoosh: require("../assets/audio/sfx/sfx_knockback_whoosh.mp3"),
  sfx_level_clear: require("../assets/audio/sfx/sfx_level_clear.mp3"),
  sfx_lightning_zap: require("../assets/audio/sfx/sfx_lightning_zap.mp3"),
  sfx_mega_blast: require("../assets/audio/sfx/sfx_mega_blast.mp3"),
  sfx_pickup_collect: require("../assets/audio/sfx/sfx_pickup_collect.mp3"),
  sfx_pickup_spawn: require("../assets/audio/sfx/sfx_pickup_spawn.mp3"),
  sfx_player_hit: require("../assets/audio/sfx/sfx_player_hit.mp3"),
  sfx_player_stun: require("../assets/audio/sfx/sfx_player_stun.mp3"),
  sfx_pop_1: require("../assets/audio/sfx/sfx_pop_1.mp3"),
  sfx_pop_2: require("../assets/audio/sfx/sfx_pop_2.mp3"),
  sfx_pop_3: require("../assets/audio/sfx/sfx_pop_3.mp3"),
  sfx_rainbow_activate: require("../assets/audio/sfx/sfx_rainbow_activate.mp3"),
  sfx_roller_impact: require("../assets/audio/sfx/sfx_roller_impact.mp3"),
  sfx_roller_loop: require("../assets/audio/sfx/sfx_roller_loop.mp3"),
  sfx_shatter: require("../assets/audio/sfx/sfx_shatter.mp3"),
  sfx_star_1: require("../assets/audio/sfx/sfx_star_1.mp3"),
  sfx_star_2: require("../assets/audio/sfx/sfx_star_2.mp3"),
  sfx_star_3: require("../assets/audio/sfx/sfx_star_3.mp3"),
  sfx_surge_alarm: require("../assets/audio/sfx/sfx_surge_alarm.mp3"),
  sfx_swap: require("../assets/audio/sfx/sfx_swap.mp3"),
  sfx_thaw: require("../assets/audio/sfx/sfx_thaw.mp3"),
  sfx_ui_back: require("../assets/audio/sfx/sfx_ui_back.mp3"),
  sfx_ui_click: require("../assets/audio/sfx/sfx_ui_click.mp3"),
  sfx_ui_hover: require("../assets/audio/sfx/sfx_ui_hover.mp3"),
  sfx_wall_rumble: require("../assets/audio/sfx/sfx_wall_rumble.mp3"),
  voice_game_over: require("../assets/audio/sfx/voice_game_over.mp3"),
  voice_go: require("../assets/audio/sfx/voice_go.mp3"),
  voice_ready: require("../assets/audio/sfx/voice_ready.mp3"),
  voice_you_win: require("../assets/audio/sfx/voice_you_win.mp3"),
} as const;

export type AudioFileId = keyof typeof AUDIO_FILES;
